server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  mail:
    host: smtp-relay.brevo.com
    port: 2525
    from: ${MAIL_FROM}
    username: ${BREVO_SMTP_USERNAME}
    password: ${BREVO_SMTP_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

external:
  api:
    quote-url: ${QUOTE_URL}

logging:
  level:
    root: INFO
    demo: INFO